# docker-compose.yml
services:
  database:
    image: mysql:8
    container_name: sgu-database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb
    ports:
      - "3307:3306"
    networks:
      - sgu-net
    volumes:
      - sgu-volume:/var/lib/mysql

  frontend:
    image: client:1.0-sgu
    build:
      context: ./client
      args:
        API_HOST: localhost
        API_PORT: 8082
        API_BASE: /sgu-api
    container_name: sgu-frontend
    ports:
      - "3000:80"
    networks:
      - sgu-net
    depends_on:
      - database

  backend:
    container_name: sgu-backend
    image: server:1.0-sgu
    build:
      context: ./service
    environment:
      SERVER_PORT: 8081
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: userdb
      DB_USER: root
      DB_PASS: root
    ports:
      - "8082:8081"
    networks:
      - sgu-net
    depends_on:
      - frontend

networks:
  sgu-net:
    driver: bridge   # <-- CAMBIA ESTO a driver: bridge (no external)

volumes:
  sgu-volume:
    driver: local    # <-- CAMBIA ESTO tambiÃ©n
